apiVersion: v1
kind: ConfigMap
metadata:
  name: prom-config-confgmap
  namespace: k8s-monitor
data:
  prometheus.yml: |-
    scrape_configs:
    - job_name: prometheus
      scrape_interval: 60s
      scrape_timeout: 10s
      static_configs:
        - targets: ['localhost:9090']
    - job_name: cadvisor
      scrape_interval: 60s
      scrape_timeout: 10s
      file_sd_configs:
      - files:
        - 'targets-cadvisor.json'
        refresh_interval: 60s
    - job_name: node-exporter
      scrape_interval: 60s
      scrape_timeout: 10s
      file_sd_configs:
      - files:
        - 'targets-nodeexporter.json'
        refresh_interval: 60s