apiVersion: v1
kind: Service
metadata:
  name: prometheus-k8s-service
  namespace: k8s-monitor
spec:
  ports:
  - port: 9090
    targetPort: prom-k8s-port
    protocol: TCP
    name: prometheus-k8s
  - port: 3000
    targetPort: listener-port
    protocol: TCP
    name: listener-k8s
  selector:
    app: prometheus-k8s